package test;
/*building and testing mazes without using recursive functions

version 1.0, 01-11-2022, only iterative methods (no recursion), mazes generated by this version are square mazes
version 1.0.1, 03-01-2026, refactored code

build: javac test/TestMaze.java

usage: java test.TestMaze [size]

	optional parameter size must be an odd value greater than 3

Note: in this class a maze is an array of cells, each cell can be an empty place or a wall or a colored place (used to perform flooding and other tasks)

maze[] contains the following values:
0: empty place
1: wall
>=2: color (used to perform flooding and other tasks)
*/

import java.util.*;

import maze.Maze;
import maze.Cell;

public class TestMaze {

	public final static int EMPTY = 0;
	public final static int WALL = 1;

	public static void main (String[] args) {
		try {
			int maze_size = 51;
			if (args.length > 0) {
				maze_size = Integer.parseInt(args[0]);
			}
			TestMaze testMaze = new TestMaze();
			testMaze.test_maze(maze_size);
		} catch (IllegalArgumentException e) {
			System.out.println("usage: java TestMaze [size]");
			System.out.println("optional parameter size must be an odd value greater than 3");
			System.exit(1);
		}
	}
	
	public void test_maze(int maze_size) throws IllegalArgumentException {
		Random random = new Random();
//out door shall be placed on the enclosure wall
		Cell out_door = new Cell(0, 1 + 2 * random.nextInt(maze_size / 2));
		Maze maze = new Maze(maze_size, out_door);
//inner cell is the typical place where a player is put at the beginning of a game
		Cell inner_cell = maze.get_inner_cell();
//check if there are cells not connected to the out door
		System.out.println("Check cells reachability: " + maze.checkReachability(out_door));
//find a path from inner cell to out door
		ArrayList<Cell> path = maze.findPathMaze(inner_cell, out_door);
//'color' path with value 2
		maze.setMaze(path, 2);
//show maze with exit path
		maze.printMaze();
		if (!path.isEmpty())
			System.out.println("Length of shortest path="+path.size());
		else System.out.println("Error: there is no path between inner cell and out");
	}

}
		