package maze;
/*class Maze generates mazes without using recursive functions to avoid stackoverflow

A maze is stored as an array of N x M squares, each square can be an empty place or a wall or a colored place (used to perform flooding and other tasks)
N and M are odd numbers greater than 3

As the maze generator uses DFS without creating loops, generated mazes have Tree structure, so player can exit simply using the hand-on-wall strategy.

maze[] contains the following values:
0: empty place
1: wall
>=2: color (used to perform flooding and other tasks)

version 1.0, 01-11-2022, only iterative methods (no recursion), mazes generated by this version are square mazes
version 1.0.1, 03-01-2026, refactored code, this version can generate also rectangulare mazes

*/

import java.util.*;

public class Maze {

	public final static int EMPTY = 0;
	public final static int WALL = 1;
	public final static int PATH = 2;

	final int N;//width of maze, including walls, must be an odd value greater than 3
	final int M;//height of maze, including walls, must be an odd value greater than 3
	final int[][] maze;
	final Cell innerCell;
	final Random random = new Random();

//	Maze(): builds a maze, note that out_door shall be on external wall
	public Maze(int n, int m, Cell out_door) throws IllegalArgumentException {
//security checks
		if ((n % 2 == 0) || (n < 5))
			throw new IllegalArgumentException("Maze: n must be an odd value greater than 3");
		if ((m % 2 == 0) || (m < 5))
			throw new IllegalArgumentException("Maze: m must be an odd value greater than 3");
		boolean isLeftWall = (out_door.x == 0);
		boolean isRightWall = (out_door.x == n - 1);
		boolean isTopWall = (out_door.y == 0);
		boolean isBottomWall = (out_door.y == m - 1);
		if (!isLeftWall && !isRightWall && !isTopWall && !isBottomWall)
			throw new IllegalArgumentException("out_door must be on an external wall");
		if ((isLeftWall || isRightWall) && (isTopWall || isBottomWall))
			throw new IllegalArgumentException("out_door cannot be in a corner");
		if ((isLeftWall || isRightWall) && (out_door.y % 2 == 0))
			throw new IllegalArgumentException("out_door.y must be odd to align with paths");
		if ((isTopWall || isBottomWall) && (out_door.x % 2 == 0))
			throw new IllegalArgumentException("out_door.x must be odd to align with paths");

		N = n;
		M = m;
		maze = new int[N][M]; //maze
//build walls both horizontal and vertical
		for (int i = 0; i < N; i++)
			for (int j = 0; j < M; j++)
				if ((i % 2 == 0) || (j % 2 == 0))
					maze[i][j] = WALL;
				else maze[i][j] = EMPTY;
//carve blocks to form maze
		Stack<Cell> queue = new Stack<>();

		int x = out_door.x;
		int y = out_door.y;
		if (x == 0) x++; 
		else if (x == N - 1) x--;
		else if (y == 0) y++;
		else if (y == M - 1) y--;

		Cell cell = new Cell(x, y);
		queue.push(cell);
		maze[x][y] = PATH;
		int[] dirs = {0, 1, 2, 3};

		while (!queue.empty()) {
			int i = cell.x;
			int j = cell.y;
			boolean found = false;

			// 4 random directions, use Fisher-Yates Shuffle
			for (int k = 3; k > 0; k--) {
				int index = random.nextInt(k + 1);
				int temp = dirs[index];
				dirs[index] = dirs[k];
				dirs[k] = temp;
			}
			for (int k = 0; k < 4; k++) {
				int dir = dirs[k];
				if ((dir == 0) && (i < N - 2) && (maze[i + 2][j] == EMPTY)) {
					maze[++i][j] = PATH;
					maze[++i][j] = PATH;
					found = true;
					break;
				} else if ((dir == 1) && (j < M - 2) && (maze[i][j + 2] == EMPTY)) {
					maze[i][++j] = PATH;
					maze[i][++j] = PATH;
					found = true;
					break;
				} else if ((dir == 2) && (i > 2) && (maze[i - 2][j] == EMPTY)) {
					maze[--i][j] = PATH;
					maze[--i][j] = PATH;
					found = true;
					break;
				} else if ((dir == 3) && (j > 2) && (maze[i][j - 2] == EMPTY)) {
					maze[i][--j] = PATH;
					maze[i][--j] = PATH;
					found = true;
					break;
				}
			}
			if (found) {
				cell = new Cell(i, j);
				queue.push(cell);
			} else cell = queue.pop();
		}
		setMaze(out_door, EMPTY);//out_door door
//now find proper inner cell, maximize distance
		int max = PATH, target_i = -1, target_j = -1;
		floodMazeDistance(out_door);
		for (int i = 1; i < N - 1; i++) {
			for (int j = 1; j < M - 1; j++) {
				if (maze[i][j] > max) {
					max = maze[i][j];
					target_i = i;
					target_j = j;
				}
			}
		}
		innerCell = new Cell(target_i, target_j);
		clearMaze();
	}

//getInnerCell(): returns the position of the inner cell, the typical place where a player is put at the beginning of a game
	public Cell getInnerCell() {
		return innerCell;
	}

//	findPathMaze(): finds path between in and out
	public ArrayList<Cell> findPathMaze(Cell in, Cell out) {
		floodMazeDistance(in);
		ArrayList<Cell> path = new ArrayList<>();
		int dist = maze[out.x][out.y];
		Cell cell = out;
	//backtrack path
		while (dist-- > PATH) { // PATH is the value of the starting point
			int i = cell.x;
			int j = cell.y;
			if (i < N - 1 && maze[i + 1][j] == dist) {
				cell = new Cell(i + 1, j);
			} else if (i > 0 && maze[i - 1][j] == dist) {
				cell = new Cell(i - 1, j);
			} else if (j < M - 1 && maze[i][j + 1] == dist) {
				cell = new Cell(i, j + 1);
			} else if (j > 0 && maze[i][j - 1] == dist) {
				cell = new Cell(i, j - 1);
			}
			path.add(cell);
		}
		clearMaze();
		return path;
	}

//	checkReachability(): check if all empty cells are reachable starting from cell in
	public boolean checkReachability(Cell in) {
		floodMazeDistance(in);
		for (int i = 1; i < N - 1; i++) {
			for (int j = 1; j < M - 1; j++) {
				if (maze[i][j] == EMPTY)
					return false;
			}
		}
		return true;
	}

//	printMazeValues(): prints cell values
	public void printMazeValues() {
		for (int j = 0; j < M; j++) {
			for (int i = 0; i < N; i++)
				System.out.print(maze[i][j]);
			System.out.println();
		}
	}

//	printMaze(): prints maze using * and . characters
	public void printMaze() {
		for (int j = 0; j < M; j++) {
			for (int i = 0; i < N; i++)
				if (maze[i][j] == EMPTY) {
					System.out.print(" ");
				} else if (maze[i][j] == WALL) {
					System.out.print("*");
				} else System.out.print(".");
				
			System.out.println();
		}
	}

//	setMaze(): set val in cell located at point p
	public void setMaze(Cell p, int val) {
		maze[p.x][p.y] = val;
	}
	
//	getMaze(): get val in cell located at point p
	public int getMaze(Cell p) {
		return maze[p.x][p.y];
	}
	
// cloneMaze(): get maze as int[][] using deep copy
    public int[][] cloneMaze() {
		int[][] copy = new int[maze.length][];
		for (int i = 0; i < maze.length; i++) {
			copy[i] = maze[i].clone(); 
		}
		return copy;
	}
	
//	setMaze(): set val along path
	public void setMaze(ArrayList<Cell> path, int val) {
		for (Cell p: path)
			maze[p.x][p.y] = val;
	}

//	clearMaze(): clear all cells different from WALL
	public void clearMaze() {
		for (int i = 0; i < N; i++) {
			for (int j = 0; j < M; j++)
				if (maze[i][j] > WALL)
					maze[i][j] = EMPTY;
		}
	}
	
//floodMazeDistance(): calculates step-by-step distances from a starting cell, for internal use only
	private void floodMazeDistance(Cell start) {
		clearMaze();
		Queue<Cell> queue = new ArrayDeque<>();
		queue.add(start);
		maze[start.x][start.y] = PATH;	
		int[][] directions = {{1, 0}, {-1, 0}, {0, 1}, {0, -1}};
		while (!queue.isEmpty()) {
			Cell cell = queue.poll();
			int i = cell.x;
			int j = cell.y;
			int distance = maze[i][j];
			for (int[] d : directions) {
				int ni = i + d[0];
				int nj = j + d[1];
				if (ni >= 0 && ni < N && nj >= 0 && nj < M && maze[ni][nj] == EMPTY) {
					maze[ni][nj] = distance + 1;
					queue.add(new Cell(ni, nj));
				}
			}
		}
	}
}